models/Games.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "game".
 *
 * @property integer $id
 * @property string $name
 * @property string $createDate
 * @property integer $creatorId
 * @property string $gameCover
 * @property string $descr
 * @property string $developer
 * @property string $publisher
 * @property integer $genreID
 *
 * @property Users $creator
 * @property GameGenre $genre
 * @property GameComments[] $gameComments
 */
class Games extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'game';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'createDate', 'creatorId', 'gameCover', 'descr', 'developer', 'publisher', 'genreID','youtubeLink'], 'required'],
            [['createDate'], 'safe'],
            [['creatorId', 'genreID'], 'integer'],
            [['descr'], 'string'],
            [['name', 'developer', 'publisher'], 'string', 'max' => 50],
            [['gameCover'], 'string', 'max' => 100],
            [['youtubeLink'], 'string', 'max' => 400]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'createDate' => 'Create Date',
            'creatorId' => 'Creator ID',
            'gameCover' => 'Game Cover',
            'descr' => 'Descr',
            'developer' => 'Developer',
            'publisher' => 'Publisher',
            'genreID' => 'Genre ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(Users::className(), ['id' => 'creatorId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGenre()
    {
        return $this->hasOne(GameGenre::className(), ['id' => 'genreID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGameComments()
    {
        return $this->hasMany(GameComments::className(), ['gameID' => 'id']);
    }

    /**
     * @inheritdoc
     * @return GameQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new GameQuery(get_called_class());
    }
}

controllers/GamesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\GameGenre;
use app\models\GameComments;
use app\models\gamesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use yii\db\Query;


/**
 * GamesController implements the CRUD actions for Games model.
 */
class GamesController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->request->isAjax) 
        {
            $session = Yii::$app->session;
            $request = Yii::$app->request;
            $comments = $request->post('comments'); 
            $gameID = $request->post('game'); 
            $model= new GameComments;
            $model->gameID=$gameID;
            $model->comments=$comments;
            $model->userID=$session['idUser'];
            $model->createDate=date('Y-m-d:H:i:s');
            $model->save(false);
            echo json_encode("OK");
        }
        $searchModel = new gamesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $this->getAllData(),
        ]);
        


    }

    function getAllData()
    {
        return Games::find()->all();
    }   


    public function get3data()
    {
        return Games::find()->orderBy(['id'=>SORT_DESC,])->limit(3)->all();
    }
    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */


    public function actionView($id)
    {
        $data = $this->findModel($id);
        $customer = GameGenre::findOne($data->genreID);
        $genre = $customer->name;
        return $this->render('view', [
            'model' => $this->findModel($id),
            'genre' => $genre,
            'comments' => GameComments::find()->where(['gameID' => $data->id])->all(),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $session = Yii::$app->session;
        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../images'));

        $model = new Games();

        if ($model->load(Yii::$app->request->post()) ) {
            $file = UploadedFile::getInstance($model, 'gameCover');
            $model->createDate = date("Y-m-d H:i:s");
            $file->saveAs(Yii::getAlias('@pathCover').'/'. $file->name);
            
            $model->gameCover = $file->name;
            $model->creatorId=$session['idUser'];
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $allGenre = ArrayHelper::map(GameGenre::find()->all(), 'id','name');
            return $this->render('create', [
                'model' => $model,
                'genreList' => $allGenre,
            ]);
        }
    }
    // Html::activeDropDownList($model, 's_id',ArrayHelper::map(Standard::find()->all(), 's_id', 'name'))
    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $allGenre = ArrayHelper::map(GameGenre::find()->all(), 'id','name');
        $model = $this->findModel($id);
        $pic_name = $model->gameCover;
        Yii::setAlias('@pathCover', realpath(dirname(__FILE__).'/../images'));
        if ($model->load(Yii::$app->request->post())) 
        {
            $file = UploadedFile::getInstance($model, 'gameCover');
            if(is_object($file))
            {
                $file->saveAs(Yii::getAlias('@pathCover').'/'. $file->name);    
                $model->gameCover = $file->name;
            }else{
                $model->gameCover = $pic_name;
            }
            
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            
            return $this->render('update', [
                'model' => $model,
                'genreList' => $allGenre,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    function actionSearch()
    {
        $model = $this->getAllData();
        // $model = new Games();
        $query = new Query;
        if(isset($_POST))
        {
            $model = Games::find()->where(['like', 'game.name', $_POST['games']['name'], ])->all();
        }
        return $this->render('searchList', [
                'model' => $model,
            ]);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    
}

views/games/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Games */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="block">
        <div class="block-bot">
          <div class="head">
            <div class="head-cnt"> 
              <h3><?= Html::encode($this->title) ?></h3>
              <div class="cl">&nbsp;</div>
            </div>
          </div>
          <div class="col-articles articles">
          
              <div class="block-bot">
                <div class="block-cnt">


    <?php $form = ActiveForm::begin(['options' => ['class' => 'cesco_form','enctype' => 'multipart/form-data']]) ?>
                    <div class="cl">&nbsp;</div>
                    <div class="fieldplace">
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                    </div>
                   
    <?php //$form->field($model, 'createDate')->textInput() ?>
<div class="fieldplace">
<?php if(isset($model->gameCover))
    {
      echo "<img src='http://".$_SERVER['SERVER_NAME']."/images/".$model->gameCover."' width=150 height=150 id='gambar' />";
    } ?>
    <?= $form->field($model, 'gameCover')->fileInput(['maxlength' => true]) ?>
    
</div>
<div class="fieldplace">
    <?= $form->field($model, 'descr')->textarea(['rows' => 6]) ?>
</div>
<div class="fieldplace">
    <?= $form->field($model, 'developer')->textInput(['maxlength' => true]) ?>
</div>
<div class="fieldplace">
    <?= $form->field($model, 'publisher')->textInput(['maxlength' => true]) ?>
</div>
<div class="fieldplace">
    <?= $form->field($model, 'youtubeLink')->textInput(['maxlength' => true]) ?>
</div>
<div class="fieldplace">
    <?php // $form->field($model, 'genreID')->textInput() ?>
<div class="form-group field-games-genreID required">
<label class="control-label" for="games-genreID">Game's Genre</label>
<div class="help-block"></div>
</div>    

<?php $dtgenreID = $model->genreID; ?>
    <select name="Games[genreID]">
              <option>--Please Select--</option>
         <?php  foreach ($genreList as $key => $value) {
                if($dtgenreID == $key)
                {
                  echo '<option selected value="'.$key.'">'.$value.'</option>  ';
                }else{
            ?>  
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
        <?php } } ?>
    </select>
</div>
<br /><br />
    <div class="fieldplace">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'submit btn-success' : 'submit btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
                </div>
              </div>   
          </div>
        </div>
      </div>

views/games/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\gamesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

     <?= // $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= //$form->field($model, 'createDate') ?>

    <?= //$form->field($model, 'creatorId') ?>

    <?= $form->field($model, 'gameCover') ?>

    <?php // echo $form->field($model, 'descr') ?>

    <?php // echo $form->field($model, 'developer') ?>

    <?php // echo $form->field($model, 'publisher') ?>

    <?php // echo $form->field($model, 'genreID') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/games/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Create Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-create">
    <?= $this->render('_form', [
        'model' => $model,
        'genreList' => $genreList,
    ]) ?>

</div>

views/games/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\gamesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    

    <?php /* GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            // 'id',
            'name',
            // 'createDate',
            // 'creatorId',
            'gameCover'=>array('format' => 'html','value' => function($data) 
                { 
                    return Html::a(Html::img('http://localhost'.Yii::$app->homeUrl.'images/'.$data['gameCover'],['width'=>'50']), ['games/view', 'id' => $data['id']], ['class' => 'profile-link']) ;
                }),
            // 'descr:ntext',
            // 'developer',
            // 'publisher',
            // 'genreID',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); */ ?>

</div>




<?php



/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */

// $this->title = 'Login';
// $this->params['breadcrumbs'][] = $this->title;

?>

 
<div class="col-articles articles">
<div class="cl">&nbsp;</div>
<?php /* GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            // 'id',
            'name',
            // 'createDate',
            // 'creatorId',
            'gameCover'=>array('format' => 'html','value' => function($data) 
                { 
                    return Html::a(Html::img('http://localhost'.Yii::$app->homeUrl.'images/'.$data['gameCover'],['width'=>'50']), ['games/view', 'id' => $data['id']], ['class' => 'profile-link']) ;
                }),
            // 'descr:ntext',
            // 'developer',
            // 'publisher',
            // 'genreID',

            ['class' => 'yii\grid\ActionColumn'],
        ],
]); */ ?>
      
<?php
$x=1;
    foreach ($model as $key => $value) 
    { ?>
        <div class="article">
            <div class="image"> <a href="<?php echo Yii::$app->request->baseUrl.'games/'.$value->id; ?>"><img src="<?php echo 'http://'.$_SERVER['SERVER_NAME'].'/images/'.$value->gameCover; ?>" alt=""></a> </div>
            <h4><a href="<?php echo Yii::$app->request->baseUrl.'games/'.$value->id; ?>"><?php echo $value->name; ?></a></h4>
            <p class="console"><strong><?php echo $value->genre->name; ?></strong></p>
        </div>
<?php
    $x++;
    if($x > 3){$x=1;echo'<div class="cl">&nbsp;</div>';}
    }
?>
            <div class="cl">&nbsp;</div>
</div>

views/games/searchList.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\gamesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-index">

    <h1><?= Html::encode($this->title) ?></h1>
</div>

<div class="col-articles articles">
<div class="cl">&nbsp;</div>
      
<?php
$x=1;
    foreach ($model as $key => $value) 
    { ?>
        <div class="article">
            <div class="image"> <a href="<?php echo Yii::$app->request->baseUrl.'games/'.$value->id; ?>"><img src="<?php echo 'http://'.$_SERVER['SERVER_NAME'].'/images/'.$value->gameCover; ?>" alt=""></a> </div>
            <h4><a href="<?php echo Yii::$app->request->baseUrl.'games/'.$value->id; ?>"><?php echo $value->name; ?></a></h4>
            <p class="console"><strong><?php echo $value->genre->name; ?></strong></p>
        </div>
<?php
    $x++;
    if($x > 3){$x=1;echo'<div class="cl">&nbsp;</div>';}
    }
?>
            <div class="cl">&nbsp;</div>
</div>

views/games/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Update Games: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="games-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'genreList' => $genreList,
    ]) ?>

</div>

views/games/view.php
<?php
$session = Yii::$app->session;          
                
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-articles articles">
<div class="cl">&nbsp;</div>

<?php if($model->creatorId == $session['idUser'])            
{ 
    echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn submit btn-primary']); 
}
?>
    <div class="article">
        <div class="image">
            <img src='<?php echo 'http://'.$_SERVER['SERVER_NAME']."/images/".$model->gameCover; ?>' alt="" />
        </div>
    </div>
    <div class="article">
        <label>Game's Name :</label><p style="color:green;"><?php echo $model->name; ?></p>
    </div>
    <br /><br /><br /><br />
    <div class="article">
        <label>Game's Description :</label><p style="color:green;"><?php echo $model->descr; ?></p>
    </div>
    <br /><br /><br /><br />
    <div class="article">
        <label>Game's Developer :</label><p style="color:green;"><?php echo $model->developer; ?></p>
    </div>
    <br /><br /><br /><br />
    <div class="article">
        <label>Game's Publisher :</label><p style="color:green;"><?php echo $model->publisher; ?></p>
    </div>
    <br /><br /><br /><br />
    <div class="videoWrapper">
    <!-- Copy & Pasted from YouTube -->
        <?php echo $model->youtubeLink; ?>
    </div>
    
    <br /><br /><br /><br />
    
  
<?php 
if($session['idUser'])
{
?>   
<textarea id='Isicomment' rows='4' cols='60' ></textarea>
<br /><br />
<button id='comment'>Comment Now</button>    
<br /><br />
<?php } ?>
<br /><br /><br /><br /><br /><br />
<h1>Comments</h1>
<br /><br />
<div>
<?php 
foreach ($comments as $key) {
?>
 <div class="tsc_clean_comment">
    <div class="comment_box fr">
      <p class="comment_paragraph" contenteditable="true"><?php echo $key->comments; ?></p>
    </div>
    <div class="avatar_box"> 
        <img src='<?php echo "http://".$_SERVER['SERVER_NAME']."/images/".$key->user->photo; ?>' height="50" width="50" alt="Avatar" class="avatar" />
        <p class="username"><?php echo $key->user->name; ?></p>
    </div>
    <div class="tsc_clear"></div>
</div>

<?php    
}
?>
</div>
<div class="cl">&nbsp;</div>
</div>
<script type="text/javascript">
$(function() {
    var gameID = '<?php echo $model->id; ?>';
    var userID = '<?php echo Yii::$app->session['idUser']; ?>';
    var url = '<?php echo "http://".$_SERVER["SERVER_NAME"]."/games"; ?>';
    var comment = "";
    $("#comment").click( function()
    {
        
        comment = $("#Isicomment").val();
        var formData = {comments:comment,game:gameID,user:userID,_csrf : '<?=Yii::$app->request->getCsrfToken()?>'};
        $.ajax({
                    url : url,
                    type: "POST",
                    data : formData,
                    success: function(data, textStatus, jqXHR)
                    {
                        location.reload(true);
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                 
                    }
                });
    });
});
</script>